### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [serialphotog/Bones#1]
Greetings, I just made a logo for your project, hope you like it.
![untitled-1](https://user-images.githubusercontent.com/35619342/39391740-54ee2ff6-4a76-11e8-9188-6bbfda7fd9fa.png)
![untitled-2](https://user-images.githubusercontent.com/35619342/39391742-564edaf8-4a76-11e8-8f7c-078ebed09ebf.png)
If you liked it, let me know which variation and I'll upload the files on a pull request. 
Also let me know if you want to add/modify something.

**Comment by serialphotog** [comment]
Those look great! I particularly like the blue one. Submit it as a pull request and I'll gladly use it. Thanks for your interest in my little hobby project!

**Comment by michaelizer** [comment]
Really glad you liked it, and you're welcome. Keep up the great work!
Done [#2](https://github.com/serialphotog/Bones/pull/2)
